export type Person = {
	name: string
	age: number
	desc: string
	image: string
	gender: 'male' | 'female'
}

export const people: Person[] = [
	{
		name: 'תמיר אדר',
		age: 38,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-75.jpg',
		gender: 'male',
	},
	{
		name: 'אלון אהל',
		age: 23,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-20.jpg',
		gender: 'male',
	},
	{
		name: 'יוסף חיים אוחנה',
		age: 24,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-40.jpg',
		gender: 'male',
	},
	{
		name: 'אבינתן אור',
		age: 31,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-54.jpg',
		gender: 'male',
	},
	{
		name: 'דרור אור',
		age: 48,
		desc: 'נחטף מבארי',
		image: '/img/people/notnim-yad-92.jpg',
		gender: 'male',
	},
	{
		name: 'גיא אילוז',
		age: 26,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-73.jpg',
		gender: 'male',
	},
	{
		name: 'הישאם אל סעיד',
		age: 36,
		desc: 'נחטף מדרום רצועת עזה',
		image: '/img/people/notnim-yad-46.jpg',
		gender: 'male',
	},
	{
		name: 'מוחמד אלעטרש',
		age: 39,
		desc: 'נחטף מעוטף עזה',
		image: '/img/people/notnim-yad-85.jpg',
		gender: 'male',
	},
	{
		name: 'לירי אלבג',
		age: 19,
		desc: 'נחטפה מנחל עוז',
		image: '/img/people/notnim-yad-7.jpg',
		gender: 'female',
	},
	{
		name: 'יצחק איציק אלגרט',
		age: 69,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-60.jpg',
		gender: 'male',
	},
	{
		name: 'חמזה אלזיאדנה',
		age: 23,
		desc: 'נחטף מחולית',
		image: '/img/people/notnim-yad-4.jpg',
		gender: 'male',
	},
	{
		name: 'יוסף אלזיאדנה',
		age: 53,
		desc: 'נחטף מחולית',
		image: '/img/people/notnim-yad-3.jpg',
		gender: 'male',
	},
	{
		name: 'עידן אלכסנדר',
		age: 20,
		desc: 'נחטף מעוטף עזה',
		image: '/img/people/notnim-yad-28.jpg',
		gender: 'male',
	},
	{
		name: 'רונן אנגל',
		age: 54,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-93.jpg',
		gender: 'male',
	},
	{
		name: 'מתן אנגרסט',
		age: 21,
		desc: 'נחטף מנחל עוז',
		image: '/img/people/notnim-yad-25.jpg',
		gender: 'male',
	},
	{
		name: 'אביב אצילי',
		age: 49,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-72.jpg',
		gender: 'male',
	},
	{
		name: 'קרינה ארייב',
		age: 20,
		desc: 'נחטפה מנחל עוז',
		image: '/img/people/notnim-yad-12.jpg',
		gender: 'female',
	},
	{
		name: 'אלקנה בוחבוט',
		age: 35,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-32.jpg',
		gender: 'male',
	},
	{
		name: 'אריאל ביבס',
		age: 5,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-62.jpg',
		gender: 'male',
	},
	{
		name: 'ירדן ביבס',
		age: 35,
		desc: 'נחטף ניר עוז',
		image: '/img/people/notnim-yad-65.jpg',
		gender: 'male',
	},
	{
		name: 'כפיר ביבס',
		age: 1,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-61.jpg',
		gender: 'male',
	},
	{
		name: 'שירי ביבס',
		age: 33,
		desc: 'נחטפה מניר עוז',
		image: '/img/people/notnim-yad-63.jpg',
		gender: 'female',
	},
	{
		name: 'אוהד בן עמי',
		age: 55,
		desc: 'נחטף מבארי',
		image: '/img/people/notnim-yad-50.jpg',
		gender: 'male',
	},
	{
		name: 'אגם ברגר',
		age: 20,
		desc: 'נחטפה מנחל עוז',
		image: '/img/people/notnim-yad-5.jpg',
		gender: 'female',
	},
	{
		name: 'אוריאל ברוך',
		age: 35,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-86.jpg',
		gender: 'male',
	},
	{
		name: 'סהר ברוך',
		age: 24,
		desc: 'נחטף מבארי',
		image: '/img/people/notnim-yad-71.jpg',
		gender: 'male',
	},
	{
		name: 'גלי ברמן',
		age: 27,
		desc: 'נחטף מכפר עזה',
		image: '/img/people/notnim-yad-44.jpg',
		gender: 'male',
	},
	{
		name: 'זיו ברמן',
		age: 27,
		desc: 'נחטף מכפר עזה',
		image: '/img/people/notnim-yad-48.jpg',
		gender: 'male',
	},
	{
		name: 'רום ברסלבסקי',
		age: 20,
		desc: 'נחטף מפסטיבל נובה',
		image: '/img/people/notnim-yad-29.jpg',
		gender: 'male',
	},
	{
		name: 'מני גודארד',
		age: 73,
		desc: 'נחטף מבארי',
		image: '/img/people/notnim-yad-84.jpg',
		gender: 'male',
	},
	{
		name: 'רן רני גאוילי',
		age: 24,
		desc: 'נחטף ממיקום לא ידוע',
		image: '/img/people/notnim-yad-95.jpg',
		gender: 'male',
	},
	{
		name: 'הדר גולדין',
		age: 23,
		desc: 'נחטף מדרום רצועת עזה',
		image: '/img/people/notnim-yad-77.jpg',
		gender: 'male',
	},
	{
		name: 'רומי גונן',
		age: 24,
		desc: 'נחטפה מפסטיבל הנובה',
		image: '/img/people/notnim-yad-9.jpg',
		gender: 'female',
	},
	{
		name: 'גיא גלבוע דלאל',
		age: 23,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-24.jpg',
		gender: 'male',
	},
	{
		name: 'דניאלה גלבוע',
		age: 20,
		desc: 'נחטפה מנחל עוז',
		image: '/img/people/notnim-yad-11.jpg',
		gender: 'female',
	},
	{
		name: "ביפין ג'ושי",
		age: 24,
		desc: 'נחטף מעלומים',
		image: '/img/people/notnim-yad-27.jpg',
		gender: 'male',
	},
	{
		name: 'אביתר דוד',
		age: 23,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-30.jpg',
		gender: 'male',
	},
	{
		name: 'איתן הורן',
		age: 38,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-57.jpg',
		gender: 'male',
	},
	{
		name: 'יאיר הורן',
		age: 46,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-53.jpg',
		gender: 'male',
	},
	{
		name: 'ענבר היימן',
		age: 27,
		desc: 'נחטפה מפסטיבל הנובה',
		image: '/img/people/notnim-yad-67.jpg',
		gender: 'female',
	},
	{
		name: 'מקסים הרקין',
		age: 36,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-33.jpg',
		gender: 'male',
	},
	{
		name: 'אילן וייס',
		age: 56,
		desc: 'נחטף מבארי',
		image: '/img/people/notnim-yad-98.jpg',
		gender: 'male',
	},
	{
		name: 'עומר ונקרט',
		age: 23,
		desc: 'נחטף מפסטיבל נובה',
		image: '/img/people/notnim-yad-14.jpg',
		gender: 'male',
	},
	{
		name: 'אריה זלמנוביץ',
		age: 85,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-76.jpg',
		gender: 'male',
	},
	{
		name: 'גד חגי',
		age: 73,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-81.jpg',
		gender: 'male',
	},
	{
		name: 'ג׳ודי ווינשטיין חגי',
		age: 70,
		desc: 'נחטפה מניר עוז',
		image: '/img/people/notnim-yad-66.jpg',
		gender: 'female',
	},
	{
		name: 'טל חיימי',
		age: 41,
		desc: 'נחטף מניר יצחק',
		image: '/img/people/notnim-yad-74.jpg',
		gender: 'male',
	},
	{
		name: 'איתי חן',
		age: 19,
		desc: 'נחטף מנחל עוז',
		image: '/img/people/notnim-yad-82.jpg',
		gender: 'male',
	},
	{
		name: 'שגיא דקל חן',
		age: 36,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-19.jpg',
		gender: 'male',
	},
	{
		name: 'אלכסנדר סשה טרופנוב',
		age: 28,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-8.jpg',
		gender: 'male',
	},
	{
		name: 'ארבל יהוד',
		age: 29,
		desc: 'נחטפה מניר עוז',
		image: '/img/people/notnim-yad-51.jpg',
		gender: 'female',
	},
	{
		name: 'אוהד יהלומי',
		age: 50,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-64.jpg',
		gender: 'male',
	},
	{
		name: 'יאיר יעקב',
		age: 59,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-91.jpg',
		gender: 'male',
	},
	{
		name: 'אליה כהן',
		age: 27,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-23.jpg',
		gender: 'male',
	},
	{
		name: 'נמרוד כהן',
		age: 20,
		desc: 'נחטף מעוטף עזה',
		image: '/img/people/notnim-yad-21.jpg',
		gender: 'male',
	},

	// TODO:
	{
		name: 'שגב כלפון',
		age: 26,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'אור לוי',
		age: 34,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'איתן לוי',
		age: 53,
		desc: 'נחטף מכביש 232',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'נעמה לוי',
		age: 20,
		desc: 'נחטפה מנחל עוז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'שי לוינסון',
		age: 19,
		desc: 'נחטף מעוטף עזה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'עודד ליפשיץ',
		age: 83,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'גדי מוזס',
		age: 80,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: "ג'ושוע לואיטו מולל",
		age: 21,
		desc: 'נחטף מנחל עוז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'איתן אברהם מור',
		age: 24,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'עמרי מירן',
		age: 47,
		desc: 'נחטף מנחל עוז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'אברה מנגיטסו',
		age: 38,
		desc: 'נחטף מצפון רצועת עזה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'שלמה מנסור',
		age: 86,
		desc: 'נחטף מכיסופים',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'אליהו מרגלית',
		age: 75,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'עומר נאוטורה',
		age: 23,
		desc: 'נחטף מעוטף עזה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'תמיר נמרודי',
		age: 19,
		desc: 'נחטף ממעבר ארז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'איתי סבירסקי',
		age: 38,
		desc: 'נחטף מבארי',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: "קית' שמואל סיגל",
		age: 65,
		desc: 'נחטף מכפר עזה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'יונתן סמרנו',
		age: 22,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'עוז דניאל',
		age: 19,
		desc: 'נחטף מכיסופים',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'צחי עידן',
		age: 50,
		desc: 'נחטף מנחל עוז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'דניאל שמעון פרץ',
		age: 22,
		desc: 'נחטף מרצועת עזה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'מתן צנגאוקר',
		age: 24,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'אריאל קוניו',
		age: 27,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'דוד קוניו',
		age: 34,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'עמירם קופר',
		age: 85,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'בר אברהם קופרשטיין',
		age: 23,
		desc: 'נחטף מפסטיבל הנובה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'עפרה קידר',
		age: 70,
		desc: 'נחטפה מבארי',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'עופר קלדרון',
		age: 53,
		desc: 'נחטף מניר עוז',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'ליאור רודאיף',
		age: 61,
		desc: 'נחטף מניר יצחק',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'אורון שאול',
		age: 20,
		desc: 'נחטף מדרום רצועת עזה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'טל שהם',
		age: 39,
		desc: 'נחטף מבארי',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'דורון שטיינברכר',
		age: 31,
		desc: 'נחטפה מכפר עזה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'עומר שם טוב',
		age: 22,
		desc: 'נחטף מפסטיבל נובה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'אלי שרעבי',
		age: 52,
		desc: 'נחטף מבארי',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'יוסי שרעבי',
		age: 53,
		desc: 'נחטף מבארי',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
	{
		name: 'עידן שתיוי',
		age: 28,
		desc: 'נחטף מפסטיבל נובה',
		image: '/img/people/notnim-yad-.jpg',
		gender: '',
	},
]
